// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgX3Sh-g7z5a3Ft2Xu02REsjccPz5pSGk',
    appId: '1:920487723086:android:979c68449f82687826431f',
    messagingSenderId: '920487723086',
    projectId: 'prime-news-media',
    storageBucket: 'prime-news-media.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD47TQYZbdlOQeQgxiMhjOJ4tnZ66TsKY0',
    appId: '1:920487723086:ios:980df9ecb49b883626431f',
    messagingSenderId: '920487723086',
    projectId: 'prime-news-media',
    storageBucket: 'prime-news-media.firebasestorage.app',
    iosBundleId: 'com.idris.primeBrower',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsf2Wot4LuXoJqqN2CONlYzRd2Nq5hY7o',
    appId: '1:920487723086:web:4bc9dca39d23fb1f26431f',
    messagingSenderId: '920487723086',
    projectId: 'prime-news-media',
    authDomain: 'prime-news-media.firebaseapp.com',
    storageBucket: 'prime-news-media.firebasestorage.app',
  );
}
